//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelProjectV2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Code { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> Gender { get; set; }
        public string NationalId { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool Sallary { get; set; }
        public bool Other { get; set; }
    }
}
